name: Keep Streamlit Alive

on:
  schedule:
    - cron: '*/4 * * * *'  # every 4 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: curl -s https://burgersinghcallcentredashboard.streamlit.app/ > /dev/null
